test: Add test to demo FFI problem
There is no _isTerminal export, but it doesn't complain about it during the build. Running the test produces:

```
SyntaxError: The requested module './foreign.js' does not provide an export named '_isTerminall'
```